name: Deploy frontend build artifact to QA server

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy_ftp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Copy .env.qa to project root
        run: cp env/.env.qa .env.qa

      - name: Build frontend to ./build
        run: npm run build:qa

      - name: Deploy build folder via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.QA_FTP_HOST }}
          username: ${{ secrets.QA_FTP_USER }}
          password: ${{ secrets.QA_FTP_PASSWD }}
          local-dir: ./build/
          server-dir: /htdocs/
